name: Detect environment
description: Pick an environment to use
outputs:
  environment:
    description: "Environment name to use. E.g. uat/production"
    value: ${{ steps.detect_environment.outputs.environment }}
  release_branch:
    description: "Release branch"
    value: ${{ steps.detect_environment.outputs.release_branch }}
runs:
  using: composite
  steps:
    - name: "Detect github environment"
      id: detect_environment
      shell: bash
      run: |
        branch=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
        echo release_branch=$branch >> $GITHUB_OUTPUT
        if [[ $branch == 'master' ]]; then
          environment=production
        elif [[ $branch == release/* ]]; then
          environment_version=${branch#release/}
          environment=$environment_version
        else
          echo "Wrong github branch used"
          exit 1
        fi
