name: Tag
description: Setup and run semantic-release
outputs:
  version:
    description: "Tag of released version"
    value: ${{ steps.result.outputs.version }}
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install node modules
      shell: bash
      run: |-
        npm install -g semantic-release \
          @semantic-release/exec \
          @semantic-release/git
    - name: Release
      shell: bash
      run: npx semantic-release
    - name: Validate release tag
      shell: bash
      run: >
        if [[ ! -f version.txt ]]; then
          echo "version.txt was not created, release aborted" 1>&2;
          exit 1;
        fi
    - id: result
      name: Persist release tag
      shell: bash
      run: |
        echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV
        echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT
